# -*- coding: utf-8 -*-
# Each treatment: slug, name, short card copy, area(s) for local SEO, and full page content.
TREATMENTS = [
  dict(slug="dental-implants", name="Dental Implants", short="Titanium root replacements for a permanent, natural-looking fix to missing teeth.",
    area="Pimple Nilakh", lede="A fixed, natural-feeling replacement for missing teeth — planned with precision and placed under Dr. Mahesh Pund's surgical expertise.",
    about="A dental implant replaces a missing tooth's root with a small titanium post, topped with a custom crown that matches your bite and smile. Unlike a bridge or denture, an implant stands independently — it doesn't rely on neighbouring teeth for support, and it stimulates the jawbone the way a natural root does. At Omax Dental, every implant case begins with detailed digital imaging so the position, angle and depth are planned before any surgery starts.",
    benefits=["Looks, feels and functions like a natural tooth", "Doesn't require reducing healthy neighbouring teeth", "Helps preserve jawbone density over time", "Built to last for decades with proper care"],
    procedure=[("Consultation &amp; Imaging","Digital X-rays assess bone quality and map the exact implant position."),
               ("Implant Placement","The titanium post is placed into the jawbone under local anaesthesia."),
               ("Healing Period","The implant fuses with the bone over several weeks — a process called osseointegration."),
               ("Crown Fitting","A custom-matched crown is attached, completing the restoration.")],
    who=["Missing one or more teeth", "Wearing a loose denture and wanting a fixed alternative", "Adequate jawbone density, or willing to discuss bone grafting", "Good general oral and gum health"],
    recovery="Mild swelling for a few days is normal and manageable with routine care. Most patients return to regular activity within 48–72 hours, with full fusion of the implant taking a few months before the final crown is placed.",
    faqs=[("Is getting a dental implant painful?","The placement is done under local anaesthesia, so discomfort during the procedure is minimal. Mild soreness afterward is typically managed with routine aftercare."),
          ("How long do dental implants last?","With good oral hygiene and regular check-ups, implants commonly last well over a decade, often decades."),
          ("Am I a candidate if I've been missing a tooth for years?","In most cases yes — a consultation with imaging will confirm bone suitability, and options like grafting exist where needed."),
          ("How many visits does the process take?","Typically two to three visits spread across the healing period, though this varies by case complexity.")]),

  dict(slug="root-canal-treatment", name="Root Canal Treatment", short="Save an infected or badly decayed tooth with gentle, modern root canal care.",
    area="Vishal Nagar", lede="Relieve deep tooth pain and save the natural tooth — performed with a precise, painless-first approach.",
    about="A root canal removes infected or inflamed pulp from inside a tooth, cleans the canal thoroughly, and seals it to prevent further infection. It's one of the most misunderstood dental procedures — done well, with modern anaesthesia, it relieves pain rather than causing it. At Omax Dental, root canal treatment is carried out with careful attention to comfort, and is often completed with far less discomfort than patients expect.",
    benefits=["Relieves persistent tooth pain at its source", "Saves the natural tooth instead of extracting it", "Stops infection from spreading to surrounding tissue", "Restored tooth can function normally afterward"],
    procedure=[("Diagnosis","A digital X-ray confirms the extent of infection and the tooth's root structure."),
               ("Cleaning the Canal","Infected pulp is carefully removed and the canal is cleaned and shaped."),
               ("Sealing","The cleaned canal is filled and sealed to prevent reinfection."),
               ("Crown Placement","A crown is usually placed over the treated tooth for long-term strength.")],
    who=["Sharp or lingering pain when biting or with hot/cold foods", "Swelling or tenderness near a specific tooth", "A tooth that has darkened after an old injury", "Deep decay reaching close to the tooth's nerve"],
    recovery="Mild sensitivity for a couple of days is normal and settles quickly. Most patients resume normal eating and daily routine the same day, with a follow-up visit to check healing before the crown is fitted.",
    faqs=[("Is a root canal really painful?","Modern anaesthesia makes the procedure itself largely painless — most of the discomfort people fear happens before treatment, from the untreated infection."),
          ("How many sittings does it need?","Most root canals are completed in one to two sittings, depending on the tooth and extent of infection."),
          ("Will the tooth need a crown afterward?","In most cases yes, since a treated tooth can become brittle and benefits from the added protection of a crown."),
          ("What happens if I delay treatment?","Delaying can allow the infection to spread, increasing pain and the risk of losing the tooth altogether.")]),

  dict(slug="full-mouth-rehabilitation", name="Full Mouth Rehabilitation", short="A complete, staged plan to rebuild function and appearance across your entire mouth.",
    area="Pimpri Chinchwad", lede="A carefully staged treatment plan that rebuilds bite, function and appearance across your entire mouth.",
    about="Full mouth rehabilitation combines multiple treatments — implants, crowns, root canals, gum therapy or bridges — into one coordinated plan for patients with extensive dental wear, decay or missing teeth. Rather than treating each tooth in isolation, we map your entire bite first, so every restoration works together. It's typically recommended after years of untreated dental issues, injury, or significant tooth loss.",
    benefits=["Restores comfortable chewing and a stable bite", "Coordinated planning avoids repeated, piecemeal treatment", "Addresses function and aesthetics together", "Long-term solution built around your whole mouth"],
    procedure=[("Comprehensive Assessment","Full imaging and bite analysis map every tooth, joint and gum condition."),
               ("Treatment Sequencing","A staged plan is built — often gum therapy first, then structural work."),
               ("Restorative Phase","Implants, crowns, bridges or root canals are carried out in planned stages."),
               ("Review &amp; Fine-Tuning","Bite and appearance are reviewed and adjusted before the plan is closed out.")],
    who=["Multiple missing, broken or heavily decayed teeth", "Longstanding bite or jaw discomfort", "Advanced gum disease affecting several teeth", "Wanting one coordinated plan instead of scattered fixes"],
    recovery="Because rehabilitation happens in planned stages, recovery is spread across the treatment timeline rather than one single event. Your doctor will walk you through what to expect after each stage before it begins.",
    faqs=[("How long does full mouth rehabilitation take?","Timelines vary by case, ranging from a few months to closer to a year for complex plans — this is discussed upfront."),
          ("Will it be done in one sitting?","No, it's completed in carefully sequenced stages so each treatment has time to heal and settle."),
          ("Is it only cosmetic?","No — the primary goal is restoring function and oral health; improved appearance follows naturally."),
          ("How is the plan customised?","It's based entirely on your imaging, bite analysis and consultation — no two rehabilitation plans are identical.")]),

  dict(slug="smile-designing", name="Smile Designing", short="A personalised cosmetic plan that reshapes your smile while keeping it natural.",
    area="Pimple Nilakh", lede="A personalised cosmetic plan — from shade to shape — designed around your face and natural smile line.",
    about="Smile designing looks at your teeth, gums, lips and facial proportions together, then plans changes — whitening, veneers, contouring or alignment — that suit you specifically, not a generic template smile. Every plan starts with a conversation about what you'd like to change, followed by digital visualisation so you can see the direction before committing to treatment.",
    benefits=["Tailored to your face shape and natural features", "Combines multiple cosmetic options into one plan", "Digital preview before any permanent treatment", "Natural-looking results, never overdone"],
    procedure=[("Consultation","We discuss what you'd like to change and review your current smile in detail."),
               ("Digital Preview","A visual plan shows the proposed shape, shade and alignment changes."),
               ("Treatment Selection","The right combination — veneers, contouring, whitening-adjacent care — is finalised."),
               ("Final Reveal","Treatments are completed and refined until the result matches the plan.")],
    who=["Uneven, chipped or discoloured teeth", "Gaps or minor misalignment affecting confidence", "Wanting a refresh before a wedding or major event", "Looking for a natural, not artificial-looking result"],
    recovery="Recovery depends on which treatments are included in your plan — cosmetic contouring needs no downtime, while veneers or alignment involve their own short adjustment periods, explained during planning.",
    faqs=[("Will my smile look natural or fake?","The goal is always a natural result matched to your face — nothing is done to make teeth look uniform or artificial."),
          ("How long does smile designing take?","Simple plans can be completed in a few visits; more involved plans combining several treatments take longer."),
          ("Can I see the result before starting?","Yes, a digital preview is part of the consultation so you know what to expect."),
          ("Is smile designing only for aesthetics?","Primarily yes, though many plans also correct minor bite or spacing issues along the way.")]),

  dict(slug="veneers", name="Veneers", short="Thin, custom shells that correct shape, colour and minor gaps in a few visits.",
    area="Wakad", lede="Thin, custom-crafted shells bonded to the front of your teeth to correct shape, colour or minor spacing.",
    about="Veneers are thin shells, custom-made to fit over the visible surface of a tooth, correcting discolouration, chips, or minor gaps without the more extensive work orthodontics would require. They're a conservative way to make a visible cosmetic change while preserving as much natural tooth structure as possible.",
    benefits=["Corrects colour, shape and minor gaps together", "Conservative — preserves most of the natural tooth", "Stain-resistant and durable with proper care", "Noticeable results in a small number of visits"],
    procedure=[("Consultation &amp; Shade Matching","Your desired look is discussed and the veneer shade is matched."),
               ("Minimal Preparation","A thin layer of enamel is prepared to allow the veneer to sit naturally."),
               ("Custom Fabrication","Veneers are custom-made to fit your exact tooth shape."),
               ("Bonding","Veneers are bonded into place and polished for a seamless finish.")],
    who=["Chipped, worn or discoloured front teeth", "Small gaps that don't need full orthodontic correction", "Teeth that are structurally healthy but cosmetically uneven", "Wanting a quicker cosmetic fix than aligners"],
    recovery="There's little to no downtime — most patients return to normal eating within a day, avoiding very hard foods on the treated teeth for the first short while.",
    faqs=[("Are veneers permanent?","They involve a small, irreversible amount of enamel preparation, so they're considered a long-term commitment rather than temporary."),
          ("How long do veneers last?","With good care, veneers commonly last a decade or more before needing replacement."),
          ("Do veneers stain like natural teeth?","They're more stain-resistant than natural enamel, though good oral hygiene still matters."),
          ("Can veneers fix crooked teeth?","They can mask minor misalignment, but significant crowding is better addressed with braces or aligners first.")]),

  dict(slug="crowns-bridges", name="Crowns &amp; Bridges", short="Restore strength to damaged teeth or replace a gap without surgery.",
    area="Pimple Nilakh", lede="Rebuild a damaged tooth's strength, or close the gap left by a missing one, without surgery.",
    about="A crown covers and protects a tooth that's been weakened by decay, a large filling, or a root canal. A bridge uses the teeth on either side of a gap to support a replacement tooth, closing the space without needing an implant. Both are custom-fabricated to match the shade and shape of your surrounding teeth.",
    benefits=["Restores strength to a compromised tooth", "Fills a gap without implant surgery", "Custom shade-matched to blend naturally", "Improves both chewing function and appearance"],
    procedure=[("Preparation","The tooth (or supporting teeth for a bridge) is gently shaped."),
               ("Impressions","Precise impressions are taken to fabricate a well-fitting restoration."),
               ("Temporary Fitting","A temporary crown or bridge protects the area while the permanent one is made."),
               ("Final Fitting","The custom-made crown or bridge is bonded and adjusted for a comfortable bite.")],
    who=["A tooth cracked, worn down or weakened after root canal", "One or more missing teeth with healthy neighbouring teeth", "Wanting a fixed, non-removable replacement option", "Needing added strength on a heavily filled tooth"],
    recovery="Mild sensitivity to temperature is common for a short period after fitting and typically settles on its own. Normal eating usually resumes within a day or two.",
    faqs=[("What's the difference between a crown and a bridge?","A crown covers a single damaged tooth; a bridge replaces a missing tooth by anchoring to the teeth beside the gap."),
          ("How long do crowns and bridges last?","Typically ten to fifteen years or longer with proper care and regular check-ups."),
          ("Will a crown look different from my other teeth?","No — crowns are shade-matched and shaped to blend in with your natural smile."),
          ("Is the procedure painful?","Local anaesthesia is used during preparation, so the procedure itself is comfortable.")]),

  dict(slug="dentures", name="Dentures", short="Comfortable, custom removable replacements for several or all missing teeth.",
    area="Pimpri Chinchwad", lede="Comfortable, custom-fitted removable teeth that restore your bite and smile when several teeth are missing.",
    about="Dentures replace multiple missing teeth with a removable appliance custom-moulded to your gums and bite. Whether partial or complete, they're built to restore chewing ability and facial support, and are fitted and adjusted over a few visits to get comfort exactly right.",
    benefits=["Restores chewing ability and facial support", "Non-surgical, removable solution", "Custom-fitted for comfort and stability", "Available as partial or complete sets"],
    procedure=[("Assessment","Your gums, jaw and remaining teeth are assessed to determine the right type."),
               ("Impressions","Detailed impressions capture the exact shape of your mouth."),
               ("Trial Fitting","A trial denture is checked for fit, bite and appearance."),
               ("Final Fitting","Adjustments are made until the final denture feels secure and natural.")],
    who=["Several or all teeth missing in one or both jaws", "Not a current candidate for implants", "Wanting a removable, budget-conscious replacement option", "Needing restored support for facial appearance"],
    recovery="A short adjustment period is normal as your mouth gets used to the new denture — minor sore spots can be refined at a quick follow-up visit.",
    faqs=[("Will dentures feel natural right away?","There's usually a short adjustment period of a couple of weeks before they feel fully natural."),
          ("Can I eat normally with dentures?","Yes, though starting with softer foods during the first few days makes the adjustment easier."),
          ("How long do dentures last?","With proper care, dentures typically last five to ten years before needing replacement or relining."),
          ("What's the difference between partial and complete dentures?","Partial dentures replace some missing teeth around existing ones; complete dentures replace an entire arch.")]),

  dict(slug="tooth-extraction", name="Tooth Extraction", short="Safe, gentle removal of a tooth that can't be saved or is causing problems.",
    area="Vishal Nagar", lede="A safe, gentle procedure when a tooth is too damaged, infected or crowded to save.",
    about="Extraction is recommended when a tooth is severely decayed, fractured, infected beyond repair, or causing crowding that affects orthodontic treatment. At Omax Dental, extractions are performed with careful attention to comfort and are always discussed as a last option after exploring whether the tooth can be saved.",
    benefits=["Removes a source of pain or infection", "Prevents infection spreading to nearby teeth", "Clears crowding where needed for orthodontic plans", "Quick procedure with clear aftercare guidance"],
    procedure=[("Assessment","An X-ray confirms the tooth's position and condition."),
               ("Anaesthesia","The area is fully numbed before any extraction begins."),
               ("Extraction","The tooth is carefully removed with minimal disturbance to surrounding tissue."),
               ("Aftercare Guidance","Clear instructions are given to support fast, comfortable healing.")],
    who=["A tooth too decayed or fractured to restore", "Severe infection unresponsive to other treatment", "Crowding that requires clearing space for orthodontics", "A stubborn baby tooth not falling out naturally"],
    recovery="Mild swelling and tenderness for a couple of days is normal. Sticking to soft foods and following aftercare instructions helps the socket heal smoothly within about a week.",
    faqs=[("Is tooth extraction painful?","The area is fully numbed beforehand, so the procedure itself is not painful; mild soreness afterward is normal and manageable."),
          ("Do I always need a replacement after extraction?","Not always, but for visible or functional teeth, options like implants or bridges are usually discussed."),
          ("How soon can I eat after an extraction?","Soft, cool foods are fine a few hours after, with normal eating resuming within a few days."),
          ("What should I avoid after extraction?","Avoid vigorous rinsing, smoking, and hard or hot foods for the first 24–48 hours to protect healing.")]),

  dict(slug="wisdom-tooth-removal", name="Wisdom Tooth Removal", short="Expert surgical removal of impacted or troublesome wisdom teeth.",
    area="Pimple Nilakh", lede="Surgical removal of impacted or troublesome wisdom teeth, handled with dedicated maxillofacial expertise.",
    about="Wisdom teeth often don't have enough room to emerge properly, becoming impacted, painful, or a source of repeated infection. Dr. Mahesh Pund's maxillofacial surgical background means impacted and complex wisdom tooth cases are handled in-house, with imaging used to plan the safest extraction approach beforehand.",
    benefits=["Relieves pain from impacted or crowded teeth", "Prevents recurring infection around the wisdom tooth", "Protects neighbouring teeth from crowding damage", "Handled by a specialist maxillofacial surgeon"],
    procedure=[("Imaging","X-rays assess the tooth's angle and position relative to nerves and bone."),
               ("Anaesthesia","The area is thoroughly numbed, with sedation options discussed if needed."),
               ("Surgical Removal","The tooth is carefully removed, with minimal disruption to surrounding tissue."),
               ("Recovery Guidance","Detailed aftercare is provided to support smooth healing.")],
    who=["Recurring pain or swelling at the back of the jaw", "A wisdom tooth only partially emerged through the gum", "Repeated infection around a wisdom tooth", "Crowding pressure on neighbouring molars"],
    recovery="Some swelling and mild discomfort for a few days is expected and manageable with routine care. Most patients are back to normal activity within a week.",
    faqs=[("Do all wisdom teeth need to be removed?","No — only when impacted, infected, or causing crowding or pain; some erupt normally and cause no issues."),
          ("Is wisdom tooth removal a major surgery?","It's a routine outpatient surgical procedure, done under local anaesthesia with sedation options where appropriate."),
          ("How long is recovery?","Most people feel back to normal within about a week, with full healing over several weeks."),
          ("Will I need someone to accompany me?","If sedation is used, arranging a companion for the day is recommended.")]),

  dict(slug="dental-fillings", name="Dental Fillings", short="Treat cavities early with tooth-coloured fillings that blend right in.",
    area="Wakad", lede="Treat cavities before they spread — with tooth-coloured fillings that blend naturally into your smile.",
    about="Fillings treat decay by removing the affected part of the tooth and restoring it with a tooth-coloured material, stopping the cavity from progressing further. Catching decay early keeps treatment simple, quick and far less invasive than waiting until a root canal or extraction becomes necessary.",
    benefits=["Stops decay from progressing further", "Tooth-coloured material blends naturally", "Quick, typically single-visit procedure", "Preserves as much natural tooth as possible"],
    procedure=[("Diagnosis","Decay is identified through examination and X-rays where needed."),
               ("Removing Decay","The decayed portion of the tooth is carefully removed."),
               ("Filling &amp; Shaping","The tooth-coloured filling is placed and shaped to match your natural bite."),
               ("Polishing","The filling is polished for a smooth, seamless finish.")],
    who=["Visible cavities or dark spots on a tooth", "Sensitivity to sweet or cold foods", "Small chips or minor tooth damage", "Routine check-up revealing early decay"],
    recovery="There's typically no downtime — you can eat normally once any local anaesthesia has worn off, usually within a couple of hours.",
    faqs=[("Are tooth-coloured fillings noticeable?","No, they're matched closely to your natural tooth shade and blend in well."),
          ("How long do fillings last?","Well-placed fillings commonly last seven to ten years or longer with good oral hygiene."),
          ("Is getting a filling painful?","Local anaesthesia keeps the procedure comfortable; most patients feel little to nothing during treatment."),
          ("Can a filling fall out?","It's uncommon with proper placement and care, though very old fillings may eventually need replacement.")]),

  dict(slug="teeth-cleaning-scaling", name="Teeth Cleaning &amp; Scaling", short="Professional cleaning that removes plaque and tartar buildup for healthier gums.",
    area="Pimple Nilakh", lede="A thorough professional clean that removes plaque and tartar buildup regular brushing simply can't reach.",
    about="Scaling removes hardened plaque (tartar) from the tooth surface and along the gumline, which brushing alone cannot remove. Regular cleaning and scaling is one of the simplest, most effective ways to prevent gum disease, bad breath and future decay, and is recommended roughly twice a year for most patients.",
    benefits=["Removes tartar buildup brushing can't reach", "Freshens breath and brightens tooth surface", "Reduces risk of gum disease over time", "Quick, comfortable, no-downtime procedure"],
    procedure=[("Examination","Gums and tooth surfaces are checked for buildup and early gum issues."),
               ("Scaling","Plaque and tartar are gently removed from teeth and the gumline."),
               ("Polishing","Teeth are polished to a smooth, clean finish."),
               ("Home-Care Guidance","Personalised tips help maintain results between visits.")],
    who=["Visible tartar or yellowing near the gumline", "Bleeding or puffy gums", "Persistent bad breath", "Anyone due for a routine six-month cleaning"],
    recovery="No downtime is needed — teeth may feel slightly sensitive for a short while, and normal eating and brushing resume immediately.",
    faqs=[("How often should I get scaling done?","Roughly every six months for most people, though your dentist may suggest a different interval based on your gum health."),
          ("Does scaling damage tooth enamel?","No, professional scaling is safe for enamel and is designed specifically to protect it by removing harmful buildup."),
          ("Will my gums bleed during scaling?","Mild bleeding can occur if gums are inflamed beforehand, and typically improves with regular cleanings."),
          ("Can scaling whiten my teeth?","It removes surface staining and buildup, which often makes teeth appear noticeably brighter, though it isn't a whitening treatment itself.")]),

  dict(slug="braces", name="Braces", short="Traditional fixed braces to correct crowding, gaps and bite issues over time.",
    area="Baner", lede="Time-tested, fixed orthodontic treatment to correct crowding, gaps and bite alignment.",
    about="Braces use fixed brackets and wires to gradually guide teeth into their correct position, addressing crowding, spacing, and bite alignment issues. They remain one of the most reliable orthodontic options, especially for more complex movements, with progress tracked through regular adjustment visits.",
    benefits=["Effective for complex crowding and bite issues", "Reliable, well-established treatment approach", "Progress monitored closely at each visit", "Suitable for both teens and adults"],
    procedure=[("Orthodontic Assessment","Imaging and impressions map your current bite and alignment."),
               ("Bracket Placement","Brackets are bonded to teeth and connected with an archwire."),
               ("Regular Adjustments","Wires are adjusted periodically to guide movement."),
               ("Retention","A retainer maintains your new alignment once braces come off.")],
    who=["Noticeably crowded or overlapping teeth", "Gaps between teeth affecting bite or appearance", "Overbite, underbite or crossbite concerns", "Complex movement needs better suited to fixed appliances"],
    recovery="Mild discomfort for a few days after placement and each adjustment is normal, easing as teeth adjust. Soft foods help during the first few days.",
    faqs=[("How long does braces treatment take?","Typically one to two and a half years, depending on the complexity of correction needed."),
          ("Are braces painful?","Some pressure and mild soreness after adjustments is normal, but it's manageable and temporary."),
          ("Can adults get braces?","Yes, braces work well for adults too, not just teenagers."),
          ("Will I need a retainer afterward?","Yes, a retainer is essential to hold teeth in their new position after braces come off.")]),

  dict(slug="invisible-aligners", name="Invisible Aligners", short="Clear, removable aligners that straighten teeth discreetly.",
    area="Hinjewadi", lede="Clear, removable aligners that straighten teeth discreetly — without metal brackets or wires.",
    about="Invisible aligners are a series of custom, transparent trays that gradually shift teeth into position, swapped out every couple of weeks as your smile progresses. They're removable for eating and brushing, and far less noticeable day-to-day than traditional braces, making them a popular choice for image-conscious adults.",
    benefits=["Virtually invisible during everyday wear", "Removable for eating, brushing and flossing", "Fewer in-clinic adjustment visits typically needed", "Digital planning shows your result in advance"],
    procedure=[("Digital Scan &amp; Planning","Impressions or a digital scan map your teeth and plan the movement sequence."),
               ("Aligner Fabrication","A custom series of clear aligners is fabricated for your treatment."),
               ("Wearing Sequence","Each aligner is worn for about two weeks before moving to the next."),
               ("Progress Checks","Periodic reviews confirm teeth are tracking to plan.")],
    who=["Mild to moderate crowding or spacing", "Wanting a discreet straightening option", "Needing a removable option for lifestyle or work reasons", "Committed to wearing aligners as directed daily"],
    recovery="Mild pressure when switching to a new aligner in the series is normal and settles within a day or two, with no impact on daily activities.",
    faqs=[("How long do I need to wear aligners each day?","Around 20–22 hours a day, removing them only to eat, brush and floss."),
          ("Are invisible aligners as effective as braces?","For mild to moderate cases, yes; more complex movements may still be better suited to traditional braces."),
          ("How often do I change aligners?","Typically every one to two weeks, following your personalised treatment sequence."),
          ("Will people notice I'm wearing them?","They're designed to be discreet and are rarely noticeable in everyday conversation.")]),

  dict(slug="pediatric-dentistry", name="Pediatric Dentistry", short="Gentle, patient dental care designed specifically for children.",
    area="Pimpri Chinchwad", lede="Gentle, patient dental care designed to make a child's visit calm, positive and cavity-free.",
    about="Children's dental needs differ from adults' — from monitoring the development of baby and permanent teeth to building comfort with dental visits early on. At Omax Dental, pediatric appointments are unhurried, explained in simple terms, and focused on building trust so future visits feel routine rather than stressful.",
    benefits=["Calm, unhurried approach suited to young patients", "Early monitoring of developing teeth and bite", "Builds positive associations with dental visits", "Preventive focus to avoid future complications"],
    procedure=[("Gentle Introduction","The visit begins with a friendly, low-pressure introduction to the clinic and chair."),
               ("Examination","Teeth and gums are checked, including monitoring of developing baby and permanent teeth."),
               ("Preventive Care","Cleaning, and guidance on brushing and diet, is provided as needed."),
               ("Parent Guidance","Parents receive clear, practical advice for at-home dental care.")],
    who=["First dental visit for a young child", "A child anxious about dental appointments", "Monitoring baby teeth or early permanent teeth", "Cavity prevention and habit-building guidance"],
    recovery="Most pediatric visits involve no downtime at all — children typically return to normal activity immediately after their appointment.",
    faqs=[("At what age should a child first visit the dentist?","Around their first birthday, or once the first tooth appears, is a good general guideline."),
          ("My child is scared of the dentist — can you help?","Yes, appointments are paced gently and explained simply to help build comfort over time."),
          ("How often should children have dental check-ups?","Roughly every six months, similar to adults, to monitor developing teeth."),
          ("Do baby teeth really need treatment if they'll fall out anyway?","Yes — untreated decay in baby teeth can affect the permanent teeth developing beneath them.")]),

  dict(slug="gum-treatment", name="Gum Treatment", short="Treat bleeding, receding or infected gums before they affect tooth stability.",
    area="Vishal Nagar", lede="Treating gum disease early protects not just your gums, but the long-term stability of your teeth.",
    about="Gum disease often starts quietly — slight bleeding when brushing, mild redness — and progresses if left untreated, eventually affecting the bone that holds teeth in place. Dr. Ashwini Jadhav-Pund's periodontal specialisation means gum treatment at Omax Dental ranges from simple deep cleaning to more advanced therapy for established gum disease.",
    benefits=["Stops gum disease before it affects tooth stability", "Reduces bleeding, swelling and discomfort", "Specialist periodontal expertise in-house", "Protects long-term investment in your natural teeth"],
    procedure=[("Periodontal Assessment","Gum pockets and bone support are measured and assessed."),
               ("Deep Cleaning","Plaque and tartar below the gumline are thoroughly removed."),
               ("Targeted Therapy","Additional periodontal therapy is applied for more advanced cases."),
               ("Maintenance Plan","A personalised recall schedule keeps gum health on track.")],
    who=["Bleeding gums when brushing or flossing", "Gums that appear red, swollen or tender", "Noticeable gum recession", "Persistent bad breath linked to gum health"],
    recovery="Mild tenderness after deep cleaning is normal for a day or two. Most patients see visible improvement in gum colour and firmness within a couple of weeks.",
    faqs=[("Can gum disease be reversed?","Early-stage gum disease (gingivitis) is often fully reversible with proper treatment and home care; more advanced disease can be managed and stabilised."),
          ("Why do my gums bleed when I brush?","Bleeding usually signals inflammation from plaque buildup and is one of the earliest signs of gum disease."),
          ("Is gum treatment painful?","Local anaesthesia is used for deep cleaning when needed, keeping the procedure comfortable."),
          ("How often should I have my gums checked?","Every six months as part of a routine check-up, or sooner if you notice bleeding or recession.")]),

  dict(slug="dental-x-ray", name="Dental X-Ray", short="Digital imaging that reveals what's happening beneath the surface.",
    area="Pimple Nilakh", lede="Digital imaging that reveals decay, infection and bone conditions invisible to the naked eye.",
    about="Digital X-rays let us see beneath the gumline and enamel — decay between teeth, infection at a root tip, bone levels, or the position of an unerupted tooth — all essential for accurate diagnosis and treatment planning. Digital imaging uses significantly lower radiation than older film methods and produces instant, detailed results.",
    benefits=["Reveals issues invisible to a visual exam", "Low-radiation digital technology", "Instant results support same-visit diagnosis", "Essential for accurate treatment planning"],
    procedure=[("Positioning","A small sensor or panoramic scanner is positioned comfortably."),
               ("Capture","The digital image is captured in seconds."),
               ("Review","Your dentist reviews the image with you on-screen."),
               ("Diagnosis &amp; Planning","Findings inform an accurate, evidence-based treatment plan.")],
    who=["First-time patients establishing a dental record", "Suspected decay between teeth or beneath fillings", "Planning for implants, extractions or orthodontics", "Routine monitoring of bone and root health"],
    recovery="There is no recovery time — X-rays are quick, comfortable, and you can continue your day immediately afterward.",
    faqs=[("Are dental X-rays safe?","Yes, digital dental X-rays use very low radiation levels and are considered safe for routine use."),
          ("How often do I need dental X-rays?","This varies by individual, typically anywhere from six months to a couple of years, based on your dental history."),
          ("Can I have an X-ray if I'm pregnant?","Please inform us if you're pregnant so appropriate precautions and timing can be discussed."),
          ("Do X-rays hurt?","No, the process is quick and painless, involving only a small sensor placed briefly in the mouth.")]),

  dict(slug="maxillofacial-surgery", name="Maxillofacial Surgery", short="Specialist surgical care for the jaw, mouth and facial structures.",
    area="Pimpri Chinchwad", lede="Specialist surgical care for complex conditions of the jaw, mouth and facial structures.",
    about="Maxillofacial surgery covers a broad range of surgical procedures involving the jaw, mouth and face — from complex extractions and cyst removal to corrective jaw procedures. Dr. Mahesh Pund's MDS specialisation in Oral &amp; Maxillofacial Surgery means these more complex cases are treated in-house with dedicated surgical expertise, rather than requiring referral elsewhere.",
    benefits=["Dedicated in-house specialist surgical expertise", "Handles complex cases beyond routine dental care", "Thorough imaging-based surgical planning", "Coordinated aftercare through recovery"],
    procedure=[("Surgical Consultation","Your condition is assessed with imaging and a detailed clinical review."),
               ("Planning","The surgical approach is planned around your specific anatomy and condition."),
               ("Procedure","Surgery is performed under appropriate anaesthesia with a focus on precision and safety."),
               ("Recovery Support","Clear aftercare instructions and follow-up guide your healing.")],
    who=["Complex or impacted tooth extractions", "Jaw, cyst or facial surgical needs", "Referrals requiring specialist surgical opinion", "Conditions affecting the jaw joint or facial bones"],
    recovery="Recovery timelines vary by procedure and are discussed in detail during your consultation, with follow-up visits scheduled to monitor healing closely.",
    faqs=[("What conditions fall under maxillofacial surgery?","This includes complex extractions, cysts and tumours, facial trauma, jaw conditions and related surgical needs."),
          ("Will I need general anaesthesia?","This depends on the specific procedure; many are done under local anaesthesia with sedation options for more complex cases."),
          ("How is a maxillofacial surgeon different from a general dentist?","A maxillofacial surgeon has additional specialised surgical training (MDS) focused specifically on the jaw, mouth and facial region."),
          ("Do I need a referral to be seen for this?","No, you can consult directly with Dr. Mahesh Pund for an assessment.")]),

  dict(slug="facial-trauma-treatment", name="Facial Trauma Treatment", short="Specialist assessment and treatment for injuries to the face and jaw.",
    area="Vishal Nagar", lede="Specialist assessment and surgical treatment for injuries affecting the jaw, teeth and facial bones.",
    about="Facial trauma — from a fall, sports injury or accident — can affect teeth, the jawbone, or surrounding facial structures. Prompt, specialist assessment matters for both function and appearance long-term. Dr. Mahesh Pund's maxillofacial surgical training covers diagnosis and treatment of these injuries, coordinated with imaging to guide the right approach.",
    benefits=["Specialist assessment of jaw and facial injuries", "Imaging-guided treatment planning", "Coordinated care for both function and appearance", "Experienced maxillofacial surgical management"],
    procedure=[("Assessment","The injury is examined and imaged to determine its full extent."),
               ("Treatment Planning","An approach is planned based on the type and severity of trauma."),
               ("Treatment","Appropriate surgical or restorative treatment is carried out."),
               ("Follow-Up Care","Healing is monitored closely with scheduled follow-up visits.")],
    who=["Jaw or facial injury from an accident or fall", "Teeth affected by a facial impact", "Persistent pain or swelling following trauma", "Seeking a specialist opinion after an injury"],
    recovery="Recovery varies significantly with the nature of the injury and is explained in detail as part of your treatment plan, with close follow-up throughout healing.",
    faqs=[("Should I see a dentist or a hospital first for facial trauma?","For severe trauma, seek emergency medical care first; for dental and jaw-related injuries once stabilised, our maxillofacial expertise can help."),
          ("Can a knocked-out tooth be saved?","In some cases yes, particularly if treated promptly — contact us as soon as possible after the injury."),
          ("Will facial trauma affect my bite permanently?","This depends on the severity and treatment; many cases recover good function with appropriate care."),
          ("Do you treat sports-related dental injuries?","Yes, sports-related facial and dental injuries are a common part of this treatment area.")]),

  dict(slug="tmj-disorders", name="TMJ Disorders", short="Diagnose and manage jaw joint pain, clicking and restricted movement.",
    area="Wakad", lede="Relief for jaw joint pain, clicking, or restricted movement affecting how you eat and speak.",
    about="The temporomandibular joint (TMJ) connects your jaw to your skull, and problems with it can cause pain, clicking sounds, or difficulty opening your mouth fully. TMJ disorders can stem from teeth grinding, stress, misalignment or joint issues, and treatment starts with identifying the underlying cause before recommending a management plan.",
    benefits=["Identifies the underlying cause of jaw pain", "Non-surgical management options considered first", "Reduces clicking, locking and jaw discomfort", "Improves comfort with eating and speaking"],
    procedure=[("Assessment","Jaw movement, bite and joint sounds are carefully evaluated."),
               ("Diagnosis","The likely cause — grinding, misalignment, stress or joint-related — is identified."),
               ("Management Plan","A tailored plan may include a night guard, bite adjustment or further referral."),
               ("Review","Progress is reviewed and the plan adjusted as needed.")],
    who=["Clicking or popping sounds when opening the jaw", "Pain around the jaw, ear or temple area", "Difficulty opening the mouth fully", "Frequent teeth grinding or clenching"],
    recovery="Most TMJ management is non-surgical and involves no downtime, with improvement typically seen gradually over weeks as the treatment plan takes effect.",
    faqs=[("What causes TMJ disorders?","Common causes include teeth grinding, jaw misalignment, stress-related clenching, or issues within the joint itself."),
          ("Is TMJ treatment surgical?","Most cases are managed non-surgically with guards, bite adjustment or lifestyle changes; surgery is reserved for select cases."),
          ("Can stress really affect my jaw?","Yes, stress-related clenching and grinding is one of the most common contributors to TMJ discomfort."),
          ("How long does TMJ treatment take to work?","Many patients notice improvement within a few weeks of starting a management plan, though this varies by cause and severity.")]),

  dict(slug="cysts-tumors-surgery", name="Cysts &amp; Tumors Surgery", short="Surgical removal of oral cysts and tumors with careful diagnosis.",
    area="Pimple Nilakh", lede="Careful diagnosis and surgical removal of cysts or growths affecting the jaw and oral tissues.",
    about="Cysts and tumours in the jaw or oral tissue are often discovered incidentally on an X-ray or during examination, and range from harmless to requiring prompt surgical attention. Accurate diagnosis comes first, often supported by imaging and biopsy, followed by surgical removal under Dr. Mahesh Pund's maxillofacial expertise where indicated.",
    benefits=["Accurate diagnosis before any surgical decision", "Specialist maxillofacial surgical removal", "Imaging-guided planning to protect surrounding structures", "Follow-up care to monitor healing"],
    procedure=[("Diagnosis","Imaging and, where needed, a biopsy confirm the nature of the growth."),
               ("Surgical Planning","The removal approach is planned around the growth's size and location."),
               ("Surgical Removal","The cyst or tumour is carefully removed under appropriate anaesthesia."),
               ("Follow-Up","Healing is monitored and any lab results are reviewed with you.")],
    who=["A growth or swelling noticed in the jaw or gum", "A cyst identified incidentally on a dental X-ray", "Persistent unexplained swelling in the oral cavity", "Referral for a suspicious oral lesion"],
    recovery="Recovery depends on the size and location of the growth removed, with clear aftercare and follow-up scheduled to monitor healing and any lab findings.",
    faqs=[("Are oral cysts usually serious?","Many are benign, but all require proper diagnosis to rule out anything more serious — this is why assessment matters."),
          ("How is a cyst or tumour diagnosed?","Through imaging and often a biopsy, which helps determine the exact nature of the growth before treatment."),
          ("Is the surgery done under general anaesthesia?","This depends on size and complexity; many cases are managed under local anaesthesia with sedation options."),
          ("Will I need follow-up after surgery?","Yes, follow-up visits monitor healing and review any laboratory findings from the removed tissue.")]),

  dict(slug="biopsy", name="Biopsy", short="Diagnostic tissue sampling for unexplained oral lesions or growths.",
    area="Pimpri Chinchwad", lede="A precise diagnostic step for unexplained oral lesions, giving clear answers before any further treatment.",
    about="A biopsy involves taking a small tissue sample from an unusual patch, sore or growth in the mouth that hasn't healed as expected, sending it for laboratory analysis to determine exactly what it is. It's a diagnostic tool, not a treatment itself — but an essential one for ruling out or identifying serious conditions early.",
    benefits=["Provides a definitive diagnosis, not a guess", "Enables early identification of serious conditions", "Minimally invasive sampling procedure", "Guides the correct next treatment step"],
    procedure=[("Examination","The lesion or area of concern is carefully examined."),
               ("Local Anaesthesia","The area is numbed to keep the sampling comfortable."),
               ("Tissue Sampling","A small sample of tissue is taken for laboratory analysis."),
               ("Results &amp; Guidance","Results are reviewed with you, along with recommended next steps.")],
    who=["A mouth sore or ulcer that hasn't healed in two weeks", "An unusual white or red patch in the mouth", "An unexplained lump or growth", "A doctor's recommendation following an oral examination"],
    recovery="The biopsy site typically heals within a week or so, with mild soreness managed easily; results are usually discussed at a scheduled follow-up.",
    faqs=[("Is a biopsy painful?","The area is numbed beforehand, so discomfort during the procedure is minimal; mild soreness afterward is normal."),
          ("How long do biopsy results take?","This varies by laboratory, but results are typically available within about one to two weeks."),
          ("Does needing a biopsy mean something serious is wrong?","Not necessarily — many biopsies confirm a benign, harmless cause; it's a precautionary diagnostic step."),
          ("What happens after I get my results?","Your doctor will explain the findings clearly and outline any recommended next steps together with you.")]),
]
